# Generated by Django 4.2.4 on 2023-08-21 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='is_comleted',
            new_name='is_completed',
        ),
    ]
